/**
 * Type declarations for Lingui compiled message files
 * This file provides TypeScript support for the .mjs files generated by @lingui/cli
 */

declare module '*/messages.mjs' {
  export const messages: Record<string, string>
}

declare module '@/locales/*/messages.mjs' {
  export const messages: Record<string, string>
}

declare module './locales/*/messages.mjs' {
  export const messages: Record<string, string>
}
